name: test
on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch: { }
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29
      - run: go test -cpu=2 -race -v ./...
      - run: go test -cpu=2 -covermode=atomic ./...

